# Generated by Django 4.1.4 on 2022-12-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='image_low_res',
            field=models.ImageField(null=True, upload_to='low_res'),
        ),
    ]
