# Generated by Django 4.1.4 on 2022-12-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_images_image_images_image_low_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_high_res',
            field=models.ImageField(null=True, upload_to='high_res'),
        ),
    ]
